export const environment = {
  rifaId: "LECHG01-",
  apiBaseUrl: "https://api.maredorazio.com/dev",
  methodsPayments: [
    {
      id: "pagomovil",
      name: "Pago Móvil",
      logo: new URL("../assets/logos/pago-movil.png", import.meta.url).href,
      coinId: "bs",
      seeds: { min: 4, step: 4, max: 96, quickAmounts: [4, 8, 12, 24, 48, 96] },
      details: [
        { label: "Cédula", value: "20242594" },
        { label: "Celular", value: "0422-6333703" },
        { label: "Banco", value: "Banco de Venezuela 0102" },
      ],
    },
    {
      id: "zelle",
      name: "Zelle",
      logo: new URL("../assets/logos/zelle.png", import.meta.url).href,
      coinId: "usd",
      seeds: { min: 4, step: 4, max: 96, quickAmounts: [4, 8, 12, 24, 48, 96] },
      details: [{ label: "Email", value: "hifreddytech@gmail.com" }],
    },
    {
      id: "transferSpei",
      name: "Transferencia SPEI",
      logo: new URL("../assets/logos/spei.jpg", import.meta.url).href,
      coinId: "mxn",
      seeds: { min: 4, step: 4, max: 96, quickAmounts: [4, 8, 12, 24, 48, 96] },
      details: [
        { label: "Banco", value: "MercadoPago" },
        { label: "CLABE", value: "722969010417786326" },
      ],
    },
    {
      id: "transferBancolombia",
      name: "Bancolombia (Transferencia)",
      logo: new URL("../assets/logos/transferencia.png", import.meta.url).href,
      coinId: "cop",
      seeds: { min: 4, step: 4, max: 96, quickAmounts: [4, 8, 12, 24, 48, 96] },
      details: [
        { label: "Banco", value: "Bancolombia" },
        { label: "Cuenta", value: "00981065221" },
        { label: "Tipo", value: "Cta de ahorros" },
        { label: "Titular", value: "Aron Hidalgo" },
      ],
    },
    {
      id: "binancePay",
      name: "Binance Pay",
      logo: new URL("../assets/logos/binance.png", import.meta.url).href,
      coinId: "usd",
      seeds: { min: 4, step: 4, max: 96, quickAmounts: [4, 8, 12, 24, 48, 96] },
      details: [{ label: "Binance ID", value: "91914887" }],
    },
  ],
  countryConfig: {
    VE: {
      name: "Venezuela",
      flag: "🇻🇪",
      currency: "USD",
      price: 0.25,
      paymentMethodIds: ["pagomovil"],
    },
    MX: {
      name: "México",
      flag: "🇲🇽",
      currency: "MXN",
      price: 4.5,
      paymentMethodIds: ["transferSpei"],
    },
    CO: {
      name: "Colombia",
      flag: "🇨🇴",
      currency: "COP",
      price: 925,
      paymentMethodIds: ["transferBancolombia"],
    },
    GLOBAL: {
      name: "Global",
      flag: "🌎",
      currency: "USD",
      price: 0.25,
      paymentMethodIds: ["binancePay", "zelle"],
    },
  },
  phoneCountries: [
    { code: "VE", flag: "🇻🇪", dialCode: "+58", name: "Venezuela" },
    { code: "CO", flag: "🇨🇴", dialCode: "+57", name: "Colombia" },
    { code: "MX", flag: "🇲🇽", dialCode: "+52", name: "México" },
    { code: "US", flag: "🇺🇸", dialCode: "+1", name: "Estados Unidos" },
    { code: "CA", flag: "🇨🇦", dialCode: "+1", name: "Canadá" },
    { code: "AR", flag: "🇦🇷", dialCode: "+54", name: "Argentina" },
    { code: "BR", flag: "🇧🇷", dialCode: "+55", name: "Brasil" },
    { code: "CL", flag: "🇨🇱", dialCode: "+56", name: "Chile" },
    { code: "EC", flag: "🇪🇨", dialCode: "+593", name: "Ecuador" },
    { code: "PE", flag: "🇵🇪", dialCode: "+51", name: "Perú" },
    { code: "BO", flag: "🇧🇴", dialCode: "+591", name: "Bolivia" },
    { code: "PY", flag: "🇵🇾", dialCode: "+595", name: "Paraguay" },
    { code: "UY", flag: "🇺🇾", dialCode: "+598", name: "Uruguay" },
    { code: "PA", flag: "🇵🇦", dialCode: "+507", name: "Panamá" },
    { code: "CR", flag: "🇨🇷", dialCode: "+506", name: "Costa Rica" },
    { code: "GT", flag: "🇬🇹", dialCode: "+502", name: "Guatemala" },
    { code: "HN", flag: "🇭🇳", dialCode: "+504", name: "Honduras" },
    { code: "SV", flag: "🇸🇻", dialCode: "+503", name: "El Salvador" },
    { code: "NI", flag: "🇳🇮", dialCode: "+505", name: "Nicaragua" },
    { code: "DO", flag: "🇩🇴", dialCode: "+1", name: "Rep. Dominicana" },
    { code: "PR", flag: "🇵🇷", dialCode: "+1", name: "Puerto Rico" },
    { code: "CU", flag: "🇨🇺", dialCode: "+53", name: "Cuba" },
    { code: "TT", flag: "🇹🇹", dialCode: "+1", name: "Trinidad y Tobago" },
    { code: "JM", flag: "🇯🇲", dialCode: "+1", name: "Jamaica" },
  ],
};
